# Use the Minimal theme
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme

# Customize your site title and description
title: "Your Name"
description: "Data Science & Sports Analytics Portfolio"
